### ISSUE TITLE
did not build

### ISSUE THREAD

**Issue by ignatandrei** [IEvangelist/blazorators#45]
I wanted to add to my list of List of Roslyn Code Generators, https://ignatandrei.github.io/RSCG_Examples/v2/docs/List-of-RSCG

But the Blazor.LocalStorage.WebAssembly.csproj  does not build on my PC  . It takes indefinitely to perform. I will put the output diagnostic below

**Comment by ignatandrei** [comment]
Obtained the file with 

dotnet build -v diag > a.txt

[a.txt](https://github.com/IEvangelist/blazorators/files/13759107/a.txt)

**Comment by ignatandrei** [comment]
Please help!

**Comment by IEvangelist** [comment]
Sorry, @ignatandrei - I'm just now seeing this. After reading through the build output, I'm not sure I see the issue. Occasionally, I've seen issues with the build where it tries accessing resources that are already being used by another process, this can happen when building from the solution - since most the libraries here are built from the source generator, which is shared. Can you try building just the `Blazor.LocalStorage.WebAssembly`?

```
dotnet build path/to/Blazor.LocalStorage.WebAssembly.csproj
```

As you can see here, the build does work - since the NuGet package is published from this repo.

- 📦 https://www.nuget.org/packages/Blazor.LocalStorage.WebAssembly
- ✅ https://github.com/IEvangelist/blazorators/actions/runs/6909134005/job/18799861947
- ⚙️ https://github.com/IEvangelist/blazorators/blob/main/.github/workflows/build-validation.yml

**Comment by ignatandrei** [comment]
I have delete the clone of the git on my laptop,. deleted the nuget cache packages .... still the same waiting....

**Comment by ignatandrei** [comment]
It happens also on another  PC ....

**Comment by IEvangelist** [comment]
I cannot reproduce this locally, or on this repo's GitHub build server. I just pulled latest on another machine too, and the build is green. I'm really not sure what to tell you, but I do want to continue to help.
![image](https://github.com/IEvangelist/blazorators/assets/7679720/92fc75e4-da99-4f62-a7e0-c2925f2accf5)

Any ideas why this might be happening?

**Comment by ignatandrei** [comment]
You are perfeclty right !  I do not know either what to do. Now it is the opposite of " it works on my machine" ;-)

**Comment by ignatandrei** [comment]
I will close for the moment. My purpose is to add your generator to my list of opinionated Roslyn Code Generators, not the build

https://ignatandrei.github.io/RSCG_Examples/v2/docs/List-of-RSCG
