### ISSUE TITLE
Trouble getting LocalStorage to work with Fluent Blazor Web App

### ISSUE THREAD

**Issue by ovation22** [IEvangelist/blazorators#59]
Trying to use LocalStorage with a Fluent Blazor Web App and I must be doing something wrong.

- Created a new Fluent Blazor Web App, `dotnet new fluentblazor -o {your project name}`
- Added `Blazor.LocalStorage.WebAssembly` to the 'Client' project
- Added `builder.Services.AddLocalStorageServices();` to 'Client' `Program.cs`
- Added `[Inject] public ILocalStorageService LocalStorage { get; set; } = null!;` to `Counter.razor`

Receiving the following error:

```
An unhandled exception occurred while processing the request.
InvalidOperationException: Cannot provide a value for property 'LocalStorage' on type 'BlazorApp3.Client.Pages.Counter'. There is no registered service of type 'Microsoft.JSInterop.ILocalStorageService'.
Microsoft.AspNetCore.Components.ComponentFactory+<>c__DisplayClass9_0.<CreatePropertyInjector>g__Initialize|1(IServiceProvider serviceProvider, IComponent component)
```

**Comment by IEvangelist** [comment]
Welcome to the world of trying to figure out render modes my friend. Believe it or not, you'd have to register this service in both the server and the client. Assuming that the render mode is auto, or server interactive, or anything besides WASM without prerendering. But since this is a WASM (browser-specific) package, that wouldn't work. So, it not this package that's the issue. In fact, you could replace this with anything and add it to DI, and then see that the server is trying to render it for the client - but doesn't have access to the service.

See here:

https://stackoverflow.com/questions/77699874/net-8-blazor-client-side-wasm-dependency-injection-not-working-in-component

As a work around, you could set the page that needs to this service to be:

```
@rendermode="new InteractiveWebAssemblyRenderMode(prerender: false)"
```
